-- 1. Create the table for access codes
create table public.access_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Enable Row Level Security (RLS)
alter table public.access_codes enable row level security;

-- 3. Create a secure function to check codes (prevents users from reading the whole table)
create or replace function check_access_code(input_code text)
returns boolean
language plpgsql
security definer -- runs with privileges of the creator
as $$
begin
  return exists (
    select 1
    from public.access_codes
    where code = input_code
    and is_active = true
  );
end;
$$;

-- 4. Insert some dummy codes for testing
insert into public.access_codes (code) values ('MERCURY-ALPHA-001'), ('TEST-CODE-123');
